---
title: "Loop to Auto Build Tabs Containing htmlwidgets"
output: html_document
---
```{r setup}

knitr::opts_chunk$set(echo = F, 
                      message = F, 
                      warning = F, 
                      results = "asis"                      )
```


```{r}

library(plotly)
library(ggplot2)
library(htmltools)
library(DataExplorer)
library(here)

```


```{r results='asis', echo = FALSE}
species_list <- unique(iris$Species) %>% paste()
species_count <- length(unique(iris$Species))
species_vec <- 1:species_count


petal_plot <- list()

  for (i_species in species_list) {

     p <- iris %>% 
      filter(Species == i_species) %>% 
      ggplot(aes(x=Petal.Length, y = Petal.Width)) +
      geom_point()
     
     ggp <- ggplotly(p)

    petal_plot[[i_species]] <- ggp

  }

sepal_plot <- list()

  for (i_species in species_list) {

     p <- iris %>% 
      filter(Species == i_species) %>% 
      ggplot(aes(x=Sepal.Length, y = Sepal.Width)) +
      geom_point()
     
     ggp <- ggplotly(p)

    sepal_plot[[i_species]] <- ggp

  }
```


```{r createChildRmdFiles, results='asis', echo = FALSE}

dir.create(path = here("scripts/temp_rmd"))

temp_rmd_list <- list()

for (species_number in species_vec) {

  species_name <- species_list[[species_number]]
  
  temp_rmd_path <- paste0("temp_rmd/", species_name, ".Rmd")
  temp_rmd_list[[species_name]] <- temp_rmd_path

  sink(file = temp_rmd_path)
  cat("  \n## ", species_list[[species_number]], "{.tabset}", "  \n", 
      "  \n### ", "Petal plot", "  \n", 
      "```{r, echo=FALSE, results = 'asis'}", "  \n",
      'htmltools::tagList(petal_plot)[[1]][[species_number]]',"  \n", 
      "```","  \n", 
      "  \n### ", "Sepal plot", "  \n",
      "```{r, echo=FALSE, results = 'asis'}", "  \n",
      'htmltools::tagList(sepal_plot)[[1]][[species_number]]',"  \n",
      "```")
  sink()
  
}
```

# Species plots

```{r knit_temp_rmd_files, echo=FALSE, results='asis'}

for (species_name in species_list) {

  # Knit the temporary RMD file
  cat(knitr::knit_child(temp_rmd_list[[species_name]],
                        quiet = TRUE))

  # Delete the temporary RMD file
  # file.remove(temp_rmd_list[[species_name]])
}

```



<!-- # Species plots -->

<!-- ```{r, child=if (length(species_vec) >= 1) 'zz_1.Rmd'} -->
<!-- ``` -->

<!-- ```{r, child=if (length(species_vec) >= 2) 'zz_2.Rmd'} -->
<!-- ``` -->

<!-- ```{r, child=if (length(species_vec) >= 3) 'zz_3.Rmd'} -->
<!-- ``` -->

<!-- ```{r, child=if (length(species_vec) >= 4) 'zz_4.Rmd'} -->
<!-- ``` -->

